name: zen_active
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  flutter_svg: ^2.0.17
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  socket_io_client: ^3.0.2
  http: ^1.3.0
  shared_preferences: ^2.5.1
  intl: ^0.20.2
  pinput: ^5.0.1
  flutter_slidable: ^4.0.0
  percent_indicator: ^4.2.4
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
  firebase_core: ^3.10.1
  rename_app: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/language/
    - assets/logo/
    - assets/svg/
    - assets/svg/rewards/
    - assets/images/
    - assets/images/faces/
    - assets/images/offline_videos/
    - assets/images/workout_plans/
    - assets/images/workout_videos/
    - assets/images/offline_videos/
    - assets/images/challenges/

  fonts:
    - family: Khula
      fonts:
        - asset: assets/fonts/Khula-Light.ttf
          weight: 300
        - asset: assets/fonts/Khula-Regular.ttf
          weight: 400
        - asset: assets/fonts/Khula-SemiBold.ttf
          weight: 600 
        - asset: assets/fonts/Khula-Bold.ttf
          weight: 700
        - asset: assets/fonts/Khula-ExtraBold.ttf
          weight: 800